[phases.setup]
nixPkgs = ["dotnet-sdk"]

[phases.build]
cmds = ["dotnet publish IlkProjem.API/IlkProjem.API.csproj -c Release -o out"]

[start]
cmd = "dotnet out/IlkProjem.API.dll --urls http://0.0.0.0:${PORT}"